name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platforms:
          - "51"
          # - "52"
          # - "68"
        templates:
          - "A"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout platforms
        uses: actions/checkout@v2
        with:
          repository: OS-Q/P${{ matrix.platforms }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: P${{ matrix.platforms }}

      - name: Checkout templates
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T${{ matrix.platforms }}${{ matrix.templates }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: T${{ matrix.platforms }}${{ matrix.templates }}

      - name: Install platforms
        if: github.repository == 'OS-Q/S03'
        working-directory: P${{ matrix.platforms }}
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        working-directory: T${{ matrix.platforms }}${{ matrix.templates }}
        if: success()
        id: build
        run: |
          pio run -d .
          echo "::set-output name=status::success"

      - name: notification
        uses: stopstopstop/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${{ matrix.platforms }}/${{ matrix.templates }}
          message: ${{steps.build.outputs.status}}

  release:
    needs:
      - build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=release_tag::release_package_$(date +"%Y.%m.%d")_${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=status::success"

      - name: Package Src
        id: package
        run: |
          echo "Platform S03 for GSM SoC" >> README.txt
          echo $(date +"%Y.%m.%d") >> README.txt
          echo ${GITHUB_REF/refs\/tags\//} >> README.txt
          echo -e "www.OS-Q.com\n" >> README.txt
          git log --stat -1 >> README.txt
          zip -r S03.zip platformio scripts setup.py
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload Firmware
        if: steps.package.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v2
        with:
          name: S03
          path: ${{ env.FIRMWARE }}/S03.zip

      - name: Upload Release
        id: upload-release
        uses: stopstopstop/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ env.FIRMWARE }}/S03.zip
            ${{ env.FIRMWARE }}/README.txt

      - name: Setup OSS
        uses: stopstopstop/ossutil-action@master
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Upload To OSS
        id: OSS
        run: |
          ossutil cp ${{ env.FIRMWARE }}/S03.zip ${{ secrets.OSS_BUCKET }} -rf
          echo "::set-output name=status::success"

      - name: Send Mail
        if: steps.rebuild.outputs.status == 'success' && !cancelled()
        uses: stopstopstop/mail-action@master
        with:
          server_address:  smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: OS-Q S03 released
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{github.event.pusher.email}}
          content_type: text/html
          convert_markdown: true
          attachments: S03.zip
          body: file://README.md
