name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      # - '**.yml'

env:
  UPLOAD_BUILD: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.9]
        platform:
          - "51"
        template:
          - "A"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P${{ matrix.platform }}/releases/latest/download/P${{ matrix.platform }}.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T${{ matrix.platform }}${{ matrix.template }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: T${{ matrix.platform }}${{ matrix.template }}

      - name: Build
        working-directory: T${{ matrix.platform }}${{ matrix.template }}
        if: success()
        id: build
        run: |
          pio run -d .
          echo "::set-output name=status::success"
