name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: TEST P51
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P51/releases/latest/download/P51.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T51A
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: T51A

      - name: Build
        working-directory: T51A
        if: success()
        run: |
          pio run -d .

      - name: Checkout PIO
        uses: actions/checkout@v2
        with:
          repository: platformio/platformio-core
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: PIO
