name: nightly

# on:
#   schedule:
#     - cron: '0 9 * * *'
on:
  push:
    branches:
      - master

env:
  UPLOAD_BUILD: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "51"
          - "52"
          - "21"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]
        package:
          - "release"
          - "latest"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install release
        if: matrix.package == 'release'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          pio platform install https://github.com/OS-Q/P${{ matrix.platform }}/releases/latest/download/P${{ matrix.platform }}.zip

      - name: Install latest
        if: matrix.package == 'latest' && github.repository == 'OS-Q/S03'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P${{ matrix.platform }}/archive/master.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T${{ matrix.platform }}A
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: T${{ matrix.platform }}

      - name: Build
        id: build
        working-directory: T${{ matrix.platform }}
        if: success()
        run: |
          mkdir build
          pio run -d . > build/log.txt
          echo "::set-output name=status::success"

      - name: Upload
        if: steps.build.outputs.status == 'success' && env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: T${{ matrix.platform }}_${{ matrix.os }}_${{ matrix.python }}_${{ matrix.package }}
          path: T${{ matrix.platform }}/build
